### ISSUE TITLE
Timeout configuration

### ISSUE THREAD

**Issue by john-griffin** [pablo-co/bamboo_postmark#11]
We occasionally see timeouts when sending to the Postmark API. Is there a way to configure the max allowed timeout? Couldn't see an obvious way of doing it. Thanks! 😄

**Comment by pablo-co** [comment]
@john-griffin  Right now there is no way to change the configuration of the request being made to Postmark. But it sounds like something that might be useful, I'll add it during the weekend. Will keep you posted.

**Comment by john-griffin** [comment]
@pablo-co thanks Pablo!

**Comment by pablo-co** [comment]
This feature was introduced in #12.

**Comment by pablo-co** [comment]
For quick reference, you can specify the timeout like this:

```elixir
config :my_app, MyApp.Mailer,
      adapter: Bamboo.PostmarkAdapter,
      request_options: [recv_timeout: 10_000] # 10 seconds
````

**Comment by john-griffin** [comment]
@pablo-co thanks, that looks perfect 😃

**Comment by joshuataylor** [comment]
Would this be the cause of `Process #PID<0.23109.3> terminating: :closed`?

Seeing this error sometimes, and the email doesn't send, stacktrace:
```
(bamboo_postmark) lib/bamboo/postmark_adapter.ex:51: Bamboo.PostmarkAdapter.deliver/2
(elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
(stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by john-griffin** [comment]
We didn't see that error, it was an explicit timeout error such as below:

```
[error] Task #PID<0.906.0> started from #PID<0.905.0> terminating 
** (Bamboo.PostmarkAdapter.ApiError) :timeout 
    lib/bamboo/postmark_adapter.ex:51: Bamboo.PostmarkAdapter.deliver/2 
```

**Comment by joshuataylor** [comment]
Seeing the following now:
```
12:55:23.130 [error] Task #PID<0.11200.0> started from #PID<0.11186.0> terminating
** (Bamboo.PostmarkAdapter.ApiError) :connect_timeout
    (bamboo_postmark) lib/bamboo/postmark_adapter.ex:51: Bamboo.PostmarkAdapter.deliver/2
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.115485522/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
    Args: []
```

But I've set a high timeout.

**Comment by pablo-co** [comment]
@joshuataylor `recv_timeout` is the timeout used when receiving a connection. `connect_timeout` is the timeout to establish a connection.

There is an [issue](https://github.com/edgurgel/httpoison/issues/215) related to this misunderstanding.

`I'm guessing the confusion is because the HTTPoison option :timeout (which corresponds to hackney :connect_timeout) returns a :connect_timeout error, whereas the HTTPoison :recv_timeout returns the :timeout hackney error. So if you get a :timeout error from :recv_timeout occuring, you would probably think to increase the :timeout option, which goes to the wrong option.`

So to fix it add `connect_timeout` to the request options.

```elixir
config :my_app, MyApp.Mailer,
      adapter: Bamboo.PostmarkAdapter,
      request_options: [recv_timeout: 10_000, connect_timeout: 10_000] # 10 seconds
````

**Comment by joshuataylor** [comment]
Ah! That's obvious when pointed out, thank you so much for the explanation @pablo-co . Have you seen this at all? Could be because our servers are located in Australia, and could have minor latency spikes.

**Comment by pablo-co** [comment]
It is the first time I have seen such an error actually happening, so that's a first. My guess is that there is probably an ISP in the middle causing the spikes. If you are inclined to find out if that is the case you can use [traceroute](https://support.opendns.com/hc/en-us/articles/227989007-How-to-Running-a-TCP-Traceroute) whenever you see the spikes happening. 👍
